---

common:
  unkown: 'There was an unkown error'
  general: 'There was a general application error'
mysql:
  connection_error: 'There was a database connection error, please check hostname and credentials.'
  timeout: 'There was a database timeout error'
s3:
  no_bucket: 'There is no S3 bucket by that name'
  no_access: 'Access denied to that S3 bucket'
